// <auto-generated />
using System;
using HandballCompetitionManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HandballCompetitionManager.Migrations
{
    [DbContext(typeof(HandballDbContext))]
    [Migration("20260608174223_AddIdentityAuthentication")]
    partial class AddIdentityAuthentication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppUserCompetition", b =>
                {
                    b.Property<int>("AdministratorsId")
                        .HasColumnType("int");

                    b.Property<int>("ManagedCompetitionsId")
                        .HasColumnType("int");

                    b.HasKey("AdministratorsId", "ManagedCompetitionsId");

                    b.HasIndex("ManagedCompetitionsId");

                    b.ToTable("CompetitionAdministrators", (string)null);
                });

            modelBuilder.Entity("CompetitionTeam", b =>
                {
                    b.Property<int>("CompetitionsId")
                        .HasColumnType("int");

                    b.Property<int>("TeamsId")
                        .HasColumnType("int");

                    b.HasKey("CompetitionsId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("TeamCompetitions", (string)null);
                });

            modelBuilder.Entity("GroupPhaseTeam", b =>
                {
                    b.Property<int>("GroupPhasesId")
                        .HasColumnType("int");

                    b.Property<int>("TeamsId")
                        .HasColumnType("int");

                    b.HasKey("GroupPhasesId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("GroupPhaseTeams", (string)null);
                });

            modelBuilder.Entity("HandballCompetitionManager.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OIB")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AppUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-admin-concurrency",
                            CreatedAt = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1985, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "Admin User",
                            Email = "admin@handball.local",
                            EmailConfirmed = true,
                            JMBG = "1234567890123",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@HANDBALL.LOCAL",
                            NormalizedUserName = "ADMIN@HANDBALL.LOCAL",
                            OIB = "12345678901",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "seed-admin-security",
                            TwoFactorEnabled = false,
                            UserName = "admin@handball.local"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-coach1-concurrency",
                            CreatedAt = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1979, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "Coach Horvat",
                            Email = "coach1@handball.local",
                            EmailConfirmed = true,
                            JMBG = "1234567890124",
                            LockoutEnabled = false,
                            NormalizedEmail = "COACH1@HANDBALL.LOCAL",
                            NormalizedUserName = "COACH1@HANDBALL.LOCAL",
                            OIB = "12345678902",
                            PhoneNumberConfirmed = false,
                            Role = 3,
                            SecurityStamp = "seed-coach1-security",
                            TwoFactorEnabled = false,
                            UserName = "coach1@handball.local"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-coach2-concurrency",
                            CreatedAt = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1982, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "Coach Vukovic",
                            Email = "coach2@handball.local",
                            EmailConfirmed = true,
                            JMBG = "1234567890125",
                            LockoutEnabled = false,
                            NormalizedEmail = "COACH2@HANDBALL.LOCAL",
                            NormalizedUserName = "COACH2@HANDBALL.LOCAL",
                            OIB = "12345678903",
                            PhoneNumberConfirmed = false,
                            Role = 3,
                            SecurityStamp = "seed-coach2-security",
                            TwoFactorEnabled = false,
                            UserName = "coach2@handball.local"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "seed-guest-concurrency",
                            CreatedAt = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1993, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "Guest User",
                            Email = "guest@handball.local",
                            EmailConfirmed = true,
                            JMBG = "1234567890126",
                            LockoutEnabled = false,
                            NormalizedEmail = "GUEST@HANDBALL.LOCAL",
                            NormalizedUserName = "GUEST@HANDBALL.LOCAL",
                            OIB = "12345678904",
                            PhoneNumberConfirmed = false,
                            Role = 4,
                            SecurityStamp = "seed-guest-security",
                            TwoFactorEnabled = false,
                            UserName = "guest@handball.local"
                        });
                });

            modelBuilder.Entity("HandballCompetitionManager.Models.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Competitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Zagreb",
                            EndDate = new DateTime(2025, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Croatian League 2025",
                            Season = "2024/2025",
                            StartDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            City = "Split",
                            EndDate = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Croatian Cup 2025",
                            Season = "2024/2025",
                            StartDate = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            City = "Zagreb",
                            EndDate = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Regional Championship",
                            Season = "2025",
                            StartDate = new DateTime(2025, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HandballCompetitionManager.Models.GroupPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("GroupPhases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompetitionId = 1,
                            Name = "Group A"
                        },
                        new
                        {
                            Id = 2,
                            CompetitionId = 1,
                            Name = "Group B"
                        },
                        new
                        {
                            Id = 3,
                            CompetitionId = 2,
                            Name = "Finals"
                        });
                });

            modelBuilder.Entity("HandballCompetitionManager.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Kickoff")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaintenanceHall")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("GroupId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AwayScore = 25,
                            AwayTeamId = 2,
                            CompetitionId = 1,
                            GroupId = 1,
                            HomeScore = 28,
                            HomeTeamId = 1,
                            Kickoff = new DateTime(2025, 5, 5, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            MaintenanceHall = "",
                            RoundNumber = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            AwayScore = 0,
                            AwayTeamId = 4,
                            CompetitionId = 1,
                            GroupId = 1,
                            HomeScore = 0,
                            HomeTeamId = 3,
                            Kickoff = new DateTime(2025, 5, 6, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            MaintenanceHall = "",
                            RoundNumber = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            AwayScore = 0,
                            AwayTeamId = 1,
                            CompetitionId = 1,
                            GroupId = 2,
                            HomeScore = 0,
                            HomeTeamId = 5,
                            Kickoff = new DateTime(2025, 5, 7, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            MaintenanceHall = "",
                            RoundNumber = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            AwayScore = 29,
                            AwayTeamId = 3,
                            CompetitionId = 2,
                            GroupId = 3,
                            HomeScore = 31,
                            HomeTeamId = 2,
                            Kickoff = new DateTime(2025, 5, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            MaintenanceHall = "",
                            RoundNumber = 0,
                            Status = 3
                        });
                });

            modelBuilder.Entity("HandballCompetitionManager.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GoalsScored")
                        .HasColumnType("int");

                    b.Property<int>("JerseyNumber")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Assists = 0,
                            BirthDate = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Marko",
                            GoalsScored = 0,
                            JerseyNumber = 1,
                            LastName = "Horvat",
                            Position = 1,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Assists = 12,
                            BirthDate = new DateTime(1995, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ivan",
                            GoalsScored = 45,
                            JerseyNumber = 7,
                            LastName = "Novak",
                            Position = 2,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            Assists = 8,
                            BirthDate = new DateTime(1993, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Petar",
                            GoalsScored = 52,
                            JerseyNumber = 8,
                            LastName = "Milic",
                            Position = 6,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            Assists = 15,
                            BirthDate = new DateTime(1992, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Damir",
                            GoalsScored = 38,
                            JerseyNumber = 10,
                            LastName = "Kitic",
                            Position = 7,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 5,
                            Assists = 0,
                            BirthDate = new DateTime(1988, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ante",
                            GoalsScored = 0,
                            JerseyNumber = 1,
                            LastName = "Vukovic",
                            Position = 1,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 6,
                            Assists = 10,
                            BirthDate = new DateTime(1996, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Luka",
                            GoalsScored = 48,
                            JerseyNumber = 9,
                            LastName = "Bevandic",
                            Position = 6,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 7,
                            Assists = 20,
                            BirthDate = new DateTime(1994, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Stipe",
                            GoalsScored = 35,
                            JerseyNumber = 11,
                            LastName = "Mandic",
                            Position = 7,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 8,
                            Assists = 0,
                            BirthDate = new DateTime(1989, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Goran",
                            GoalsScored = 0,
                            JerseyNumber = 1,
                            LastName = "Ivanovic",
                            Position = 1,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 9,
                            Assists = 11,
                            BirthDate = new DateTime(1997, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nikola",
                            GoalsScored = 42,
                            JerseyNumber = 5,
                            LastName = "Salic",
                            Position = 2,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 10,
                            Assists = 18,
                            BirthDate = new DateTime(1991, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Dino",
                            GoalsScored = 40,
                            JerseyNumber = 12,
                            LastName = "Grgic",
                            Position = 7,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 11,
                            Assists = 9,
                            BirthDate = new DateTime(1994, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Zoran",
                            GoalsScored = 46,
                            JerseyNumber = 13,
                            LastName = "Milic",
                            Position = 6,
                            TeamId = 5
                        });
                });

            modelBuilder.Entity("HandballCompetitionManager.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoachName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("int");

                    b.Property<string>("HomeArena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoachName = "Coach Horvat",
                            FoundedYear = 2005,
                            HomeArena = "Arena Zagreb",
                            HomeCity = "Zagreb",
                            Name = "Zagreb Handball"
                        },
                        new
                        {
                            Id = 2,
                            CoachName = "Coach Vukovic",
                            FoundedYear = 2008,
                            HomeArena = "Gradski Vrt",
                            HomeCity = "Split",
                            Name = "Split Warriors"
                        },
                        new
                        {
                            Id = 3,
                            CoachName = "Coach Ivanovic",
                            FoundedYear = 2003,
                            HomeArena = "Mladost Arena",
                            HomeCity = "Rijeka",
                            Name = "Rijeka Sharks"
                        },
                        new
                        {
                            Id = 4,
                            CoachName = "Coach Grgic",
                            FoundedYear = 2010,
                            HomeArena = "Gradski Vrt Osijek",
                            HomeCity = "Osijek",
                            Name = "Osijek Titans"
                        },
                        new
                        {
                            Id = 5,
                            CoachName = "Coach Milic",
                            FoundedYear = 2006,
                            HomeArena = "Zadar Arena",
                            HomeCity = "Zadar",
                            Name = "Zadar Eagles"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AppUserCompetition", b =>
                {
                    b.HasOne("HandballCompetitionManager.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AdministratorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HandballCompetitionManager.Models.Competition", null)
                        .WithMany()
                        .HasForeignKey("ManagedCompetitionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompetitionTeam", b =>
                {
                    b.HasOne("HandballCompetitionManager.Models.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HandballCompetitionManager.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupPhaseTeam", b =>
                {
                    b.HasOne("HandballCompetitionManager.Models.GroupPhase", null)
                        .WithMany()
                        .HasForeignKey("GroupPhasesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HandballCompetitionManager.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HandballCompetitionManager.Models.GroupPhase", b =>
                {
                    b.HasOne("HandballCompetitionManager.Models.Competition", "Competition")
                        .WithMany("Groups")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("HandballCompetitionManager.Models.Match", b =>
                {
                    b.HasOne("HandballCompetitionManager.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HandballCompetitionManager.Models.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HandballCompetitionManager.Models.GroupPhase", "GroupPhase")
                        .WithMany("Matches")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HandballCompetitionManager.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("Competition");

                    b.Navigation("GroupPhase");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("HandballCompetitionManager.Models.Player", b =>
                {
                    b.HasOne("HandballCompetitionManager.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("HandballCompetitionManager.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("HandballCompetitionManager.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HandballCompetitionManager.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("HandballCompetitionManager.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HandballCompetitionManager.Models.Competition", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("HandballCompetitionManager.Models.GroupPhase", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("HandballCompetitionManager.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
